### ISSUE TITLE
What are realistic timeline goals for coalescing around a standard?

### ISSUE THREAD

**Issue by jakerockland** [0xfoobar/token-delegation#14]
Knowing what the goals are with regards to coalescing around approach here would be helpful to know for client teams thinking about how they may make use of something like this in the future.

**Comment by 0xfoobar** [comment]
My thinking is that first-mover with adoption generally beats perfection. Would be looking to launch as soon as there's the first big "adopter" agreeing to use it. Adopter being an NFT platform or NFT project which wants to integrate the delegation registry into their drop.

**Comment by jakerockland** [comment]
> My thinking is that first-mover with adoption generally beats perfection. Would be looking to launch as soon as there's the first big "adopter" agreeing to use it. Adopter being an NFT platform or NFT project which wants to integrate the delegation registry into their drop.

Strongly agree that perfection is the enemy of progress. 

Not sure if we'd be the first depending on timeline of this realistically being ready + feature complete (getting contract spec finalized feels like it is making progress, but relatedly there are still some open questions I have about where a generalized UI for this registry may live that aren't application/client-specific) have some possible use cases that come to mind for us at Art Blocks FWIW and would love to consider updating our Merkle-proof minter and token-gated minter implementations to be compatible with the registry if that timeline works out...

cc @ryley-o

**Comment by 0xfoobar** [comment]
Not sure if you saw this, but got a "neutral" frontend up, calling it "Delegate Cash": https://goerli.delegate.cash/

**Comment by jakerockland** [comment]
> Not sure if you saw this, but got a "neutral" frontend up, calling it "Delegate Cash": https://goerli.delegate.cash/

AHA! I had not seen that, that is awesome 🔥 

Is there a place where the code for this frontend lives?

**Comment by 0xfoobar** [comment]
Pinging the guy who made it, will see if this can be opensourced shortly

**Comment by jakerockland** [comment]
> Pinging the guy who made it, will see if this can be opensourced shortly

Fantastic–if so would be awesome to just pull into the same repo here for better visibility/transparency.

**Comment by 0xGh** [comment]
Pretty awesome idea. Can it be used for NFT "rental/lending"?

**Comment by jakerockland** [comment]
We may be able to close this issue now that we've coalesced to the point of kicking off EIP process: https://eips.ethereum.org/EIPS/eip-5639

WDYT @0xfoobar ?
