### ISSUE TITLE
How should we recognize all contributors in final deployed standard?

### ISSUE THREAD

**Issue by jakerockland** [0xfoobar/token-delegation#15]
Filed as a result of conversation here, for further discussion: https://github.com/0xfoobar/nft-delegation/pull/13#discussion_r947283618 😄 💜 

cc @0xfoobar @wwhchung

**Comment by 0xfoobar** [comment]
Should recognize everybody imo, this doesn't need to be a "foobar" thing

**Comment by jakerockland** [comment]
Ah sorry the question here is more pragmatically how we want to do so–using an `author` tag, having a `contributors` block in a code comment before deploy, etc.

I have no strong opinions :shrug

**Comment by wwhchung** [comment]
I made this change in my pull request.

**Comment by ryley-o** [comment]
oops I forgot to add myself in my PR 😅

**Comment by jakerockland** [comment]
> oops I forgot to add myself in my PR 😅

hehe sounds like another PR

**Comment by 0xfoobar** [comment]
Copied the Seaport format in #21
