### ISSUE TITLE
Delegation for custom roles

### ISSUE THREAD

**Issue by TheXienator** [0xfoobar/token-delegation#19]
I saw the Fully Extensible section in the README but did not see this in the contract yet. Is this something that is still in progress or is it something I can try making a PR for? 

```
Fully Extensible, User-Defined Roles
Why? Because we can't anticipate all the future use cases for delegation today. The registry should accomodate novel and distinct roles, via an [EIP-165-esque hashlist](https://eips.ethereum.org/EIPS/eip-165) for specific permissions. We will hardcode NFT-specific methods to ease adoption as well.
```

I was thinking of adding a method something along the lines of `delegateForHash(address, address, bytes32, bool)` and the corresponding check and revoke methods as well.

**Comment by 0xfoobar** [comment]
Good catch, ended up removing that because the additional complexity and offchain coordination it entailed didn't seem worth the benefits. See the discussion at https://github.com/0xfoobar/nft-delegation/issues/8
