### ISSUE TITLE
Onchain Enumeration

### ISSUE THREAD

**Issue by 0xfoobar** [0xfoobar/token-delegation#2]
Currently delegations can be parsed offchain through event emission, and then checked onchain by calling the read methods on the delegation registry.

This is doable but requires more integration work for frontend developers. Is there a way to add onchain enumerability or legibility without introducing excessive complexity or gas costs?

**Comment by ryley-o** [comment]
One way this could be achieved via `mapping(address => userDelegations) delegations`, where `userDelegations` is an enumerable set of a given vault's delegation hashes that currently have a value of `true` (ref: https://docs.openzeppelin.com/contracts/4.x/api/utils#EnumerableSet). That would enable a user to enumerate their delegation hashes.

Additionally, if we want to give a user even more information, a mapping that describes what each userDelegation hash describes could be achieved via 
```
struct DelegateInfo {
    address delegate;
    bytes32 role;
    // contract null if delegating to all 
    address contract;
    // tokenId null if delegating to contract or all
    uint256 tokenId
}
mapping(bytes32 => DelegateInfo) public delegateHashToDelegateInfo;
```

This type of solution would probably negligibly affect read calls (just check if hash is in vault's set, O(1) and efficient). It would add gas cost to user calls to write functions, especially if we stored the entire DelegateInfo on-chain.

**Comment by jakerockland** [comment]
Generally am a fan of the above approach @ryley-o 👍 !vibe

**Comment by 0xfoobar** [comment]
Added in #20
