### ISSUE TITLE
Multiple Delegation

### ISSUE THREAD

**Issue by 0xfoobar** [0xfoobar/token-delegation#3]
Currently users can only delegate to one address at a time.

Two questions:
(1) Should users be able to delegate to multiple addresses at a time? Why or why not?
(2) How does this impact revocations?

Once these are resolved implementation can begin.

**Comment by jakerockland** [comment]
Are there any explicitly known use-cases (e.g. clients that want this) for multiple delegation? To me it would seem that use cases where multiple delegation may be helpful are also probably well served by revoking-and-delegating-to-new-delegate, but that multiple delegation itself isn't a clear value proposition to me personally. 

That said, I think if implemented in the right way interface-wise, it probably doesn't add complexity to the client-integration side of things for dApps like Art Blocks, but does potentially pass on unnecessary gas costs to users if it adds complexity in the delegate-checking-logic which is not ideal if there is not a clear use-case for multiple delegation.

**Comment by ryley-o** [comment]
I think in its current state, users can delegate to >1 hot wallet, but can only delegate to a single address per call?.
@0xfoobar - Is this issue to determine if users should be able to add >1 delegate per call?

**Comment by 0xfoobar** [comment]
No explicitly known use-cases I can think of other than users having multiple hot wallets (one on phone, one on computer), so I'm leaning against thinking multiple delegation isn't super important compared to other features like onchain queryability. Just want to make sure I'm not missing any explicit use cases others might have @jakerockland @ryley-o

**Comment by jakerockland** [comment]
I can't think of any explicit use cases personally (other than multiple hot wallets, one computer, one phone, but even in that case if they're hot wallets they could also _probably_ have the same private keys...). That said, I don't feel super strongly about this, just seems like it adds potentially unnecessary complexity.

**Comment by 0xfoobar** [comment]
Added in #20
