### ISSUE TITLE
Batch Revoke

### ISSUE THREAD

**Issue by 0xfoobar** [0xfoobar/token-delegation#4]
Currently users have to revoke permissions one-at-a-time. Is there a way to help them revoke everything in a single transaction in case their hot wallet is compromised?

**Comment by jakerockland** [comment]
This feels much simpler to implement if we get rid of the `role` concept, see #8

**Comment by ryley-o** [comment]
This could be implemented with an additional safety switch: `mapping(address => bool) revokeAll`, able to be configured by the sender.
That kind of solution would require an additional SLOAD per check though (to ensure revokeAll is not true).

**Comment by 0xRusowsky** [comment]
> 

The problem with this approach is that if the owner decides to delegate again (after calling `revokeAll`), they would need to un-revoke. Therefore, the previous delegations would become valid again. This behavior doesn't seem to be user-friendly nor security focused to me.

**Comment by 0xfoobar** [comment]
> This feels much simpler to implement if we get rid of the `role` concept, see #8

Agreed, otherwise you rely on offchain parsing and complex calldata at a minimum. Not what people are looking for in the heat of the moment after a wallet compromise.

**Comment by 0xfoobar** [comment]
Added in #13
