### ISSUE TITLE
Timelocked Delegation

### ISSUE THREAD

**Issue by 0xfoobar** [0xfoobar/token-delegation#5]
Currently delegations have no expiry but can be revoked at any time. Is a timelock feature desirable? Note that delegations do not have power over token ownership, so the vault can transfer the token at any time to do a soft revocation.

**Comment by jakerockland** [comment]
I'm not convinced that timelocked delegation is a necessary feature set; however, I do have a strong opinion that if it is added as a feature set, it should be an explicit opt-in/opt-out type of behavior at the time of delegation TX, as opposed to something that is some implicit default behavior (even if documented) of the delegation smart contract).

**Comment by 0xfoobar** [comment]
Agree on both

**Comment by 0xRusowsky** [comment]
If just submitting a PR with my proposal for delegations that can expire

**Comment by jakerockland** [comment]
> I've just submitting a PR with my proposal for delegations that can expire

Awesome–I dig it, added some thoughts on the PR.

**Comment by 0xfoobar** [comment]
Decided against time-based expiration for simplicity and parallel interfaces with ERC20/721/1155 approvals
